import LegalPage, {
  Section, P, List, LI, B, Callout, Facts,
  ORG, BRAND, SITE, SUPPORT_EMAIL,
} from "./LegalPage";

export default function Terms() {
  return (
    <LegalPage
      title="Terms of Service"
      subtitle={`The agreement between you and ${ORG} when you use ${BRAND}. Short, and in plain words, because terms nobody reads protect nobody.`}
    >
      <Section n="1" title="The agreement">
        <P>
          By using {BRAND} at {SITE} you agree to these terms. If you do not, please
          do not use the service. You must be 18 or older and able to enter a
          contract under Indian law.
        </P>
      </Section>

      <Section n="2" title="What the service does">
        <P>
          {BRAND} collects news in the categories you choose, ranks what is worth
          covering, and writes video scripts in a style learned from videos you
          supply. It also writes titles, descriptions and hashtags, and can produce
          an English version of a script.
        </P>
        <Callout>
          <B>{BRAND} writes drafts. You are the publisher.</B> Every script is a
          starting point that you are expected to read, check and edit before it
          goes anywhere near your audience.
        </Callout>
      </Section>

      <Section n="3" title="Credits, and how billing works">
        <Facts
          rows={[
            ["No subscription", "Credits are bought once and never expire. Nothing recurs, and there is nothing to cancel."],
            ["New accounts", "Start with 90 free credits, enough to try the product properly before paying anything."],
            ["What a script costs", "Priced by finished length: one credit buys two seconds of script. The exact cost is shown on the button before you press it."],
            ["Add-ons", "An English version and the title/description/hashtag pack are priced separately and shown before you order."],
            ["Payments", "Handled by Razorpay in Indian Rupees. We never see your card details."],
          ]}
        />
        <P>
          Prices can change, but a price you were shown at the moment you pressed the
          button is the price you pay. Credits already in your wallet keep their
          value.
        </P>
      </Section>

      <Section n="4" title="Your videos and your voice">
        <P>
          You keep ownership of everything you upload. By adding a video you confirm
          you own it or have the right to use it, and you give us permission to read
          it and build a voice profile for your account alone.
        </P>
        <P>
          You may not add someone else's videos to imitate them. It is the one thing
          here that can genuinely harm a third party, and it will get an account
          closed.
        </P>
      </Section>

      <Section n="5" title="Who owns the scripts">
        <P>
          <B>You do.</B> Scripts written for your account are yours to publish,
          edit, monetise and licence as you see fit. We claim no ownership and take
          no cut of anything you earn from them.
        </P>
      </Section>

      <Section n="6" title="What we do not promise">
        <P>
          Scripts are generated by an AI model from public news sources. We take
          accuracy seriously and the model is instructed to use only the source
          material supplied to it, but:
        </P>
        <Callout tone="warn">
          <B>Check every fact before you say it out loud.</B> We do not guarantee
          that a script is accurate, original, or fit for publication. Every script
          shows the sources it was written from, so you can check them. Doing so is
          your responsibility, not ours.
        </Callout>
        <P>
          We also do not promise any particular result: no view count, no growth, no
          revenue, and no ranking on any platform.
        </P>
      </Section>

      <Section n="7" title="Acceptable use">
        <P>You agree not to use {BRAND} to:</P>
        <List>
          <LI>Impersonate another creator or build a voice from videos that are not yours.</LI>
          <LI>Produce content that is unlawful, defamatory, hateful, or harmful to a real person.</LI>
          <LI>Publish claims you have not checked, in a way that misleads your audience.</LI>
          <LI>Resell, scrape or automate access to the service outside its normal use.</LI>
          <LI>Attempt to break, overload, or work around the limits of the platform.</LI>
        </List>
      </Section>

      <Section n="8" title="Availability">
        <P>
          We aim to keep {BRAND} running, but we do not guarantee uninterrupted
          service. It depends on third parties (Google, news sources, payment
          providers) that can fail independently of us. Daily generation limits
          apply to keep the service usable for everybody.
        </P>
      </Section>

      <Section n="9" title="Ending it">
        <P>
          You may stop using {BRAND} at any time and ask us to delete your account.
          We may suspend or close an account that breaks these terms, particularly
          section 4 or 7. If we close your account for something other than a breach,
          we will refund unused credits.
        </P>
      </Section>

      <Section n="10" title="Liability">
        <P>
          To the extent Indian law allows, our total liability for any claim arising
          from your use of {BRAND} is limited to the amount you paid us in the twelve
          months before the claim. We are not liable for lost profits, lost views, or
          consequences of publishing a script you did not check.
        </P>
      </Section>

      <Section n="11" title="Governing law">
        <P>
          These terms are governed by the laws of India. Courts at Hyderabad,
          Telangana have exclusive jurisdiction.
        </P>
      </Section>

      <Section n="12" title="Changes">
        <P>
          We may update these terms. The date at the top changes when we do, and
          material changes will be emailed to you before they take effect. Questions
          go to{" "}
          <a href={`mailto:${SUPPORT_EMAIL}`} style={{ color: "var(--ink)", fontWeight: 600 }}>
            {SUPPORT_EMAIL}
          </a>.
        </P>
      </Section>
    </LegalPage>
  );
}
